### PR TITLE
Update CookieHacker.h

### PR DESCRIPTION
**Pull request by Sellyme**
Correcting typo (yuor→your).

### CODE REVIEW

**Comment by vicksonzero** [comment]
oops. i believe i didn't make the same mistake in the game did i?

**Comment by vicksonzero** [comment]
Thanks

**Comment by Sellyme** [comment]
All flavour text appears correct at version 1.3.2-release in-game.

**Comment by vicksonzero** [comment]
thanks for your help and enthusiasm

**Pull request merged**
